### ISSUE TITLE
Needs coding guidelines.

### ISSUE THREAD

**Issue by Longhanks** [fredericmeyer/nanoboyadvance#9]
The code style in the project differs a lot.
- (Previously) snake case in Qt for non-Qt additions, Qt is camel case
- Methods starting with upper case in GBA classes
- No uniform decisions concerning 
  - Braces/newlines
  - private/protected/public or public/protected/private order
  - include order
  - Tabs vs spaces
  - Exceptions or other ways of error handling
  - C-style pointer passing or C++ const references? (Highly plead for const references)

We need to make sure the project stays readable and thus decide what the official coding style will be.

**Comment by fredericmeyer** [comment]
You're the variation in code style is mainly due to a lot of refactoring which recently started to happen
and still is in process. 

Generally speaking:
I can agree that we refactor all method names to start with a lower case letter.
Also in future members will be named m_MyMember everywhere (also in the Qt part) 

- Newlines for braces, for one-liners don't use braces at all.
- Protection level: Generally try to do private, protected then public. However the generel order of a class 
  should be Definitions (const vars, enums, inline methods) then methods and finally class members.
- Include order: Generally our own code should be included before any library. I somehow like this more.
- Tabs vs spaces: Spaces of course, everything else is insane.
- Exceptions: Currently stay with exceptions but recommend a better way of error handling and we can talk about it.
- C vs C++ styles: I tend to dislike C++ const references because they hide what is actually being done.

**Comment by Longhanks** [comment]
I'm perfectly fine with the first 4 bullets.

Concerning exceptions: There are many solutions out there, ranging from simple C-style return values of -1 up to return enums or optionals. The LLVM project describes what I agree with why we should avoid exceptions: 

> In an effort to reduce code and executable size, LLVM does not use RTTI (e.g. dynamic_cast<>) or exceptions. These two language features violate the general C++ principle of "you only pay for what you use", causing executable bloat even if exceptions are never used in the code base, or if RTTI is never used for a class. Because of this, we turn them off globally in the code.

Also, keep in mind that if you want to port the project to different platforms, many ship without exceptions enabled (and some even forbid using them at all). I don't know the special cases, but since you told me the 3DS is a long term goal, according to [StackExchange](http://programmers.stackexchange.com/a/113481), most to all consoles deactivate exception support. Since there are very few exceptions in the project up until now, refactoring them out is much easier to do now than later when the project has grown.

As to the references, they provide several advantages compared to pointers. I wouldn't generally say using pointers makes it more clear what's being done, could you elaborate on that?
The const semantics and getting rid of undefined behavior when dereferencing certainly makes the code safer. [Here](http://stackoverflow.com/a/7058373) is another StackOverflow discussion about the topic. If there is any special piece of code you have in mind, let's talk about it and see why pointers might be more appropriate. I'd recommend the rule of thumb of trying to use references when possible and using pointers as fallbacks, as mentioned in the StackOverflow post, though.
